### ISSUE TITLE
Competencies - Functionality

### ISSUE THREAD

**Issue by mwtsn** [mkdo/cpd#1]
Open discussion to how we handle competencies functionality in the CPD System. 

- How is the functionality currently handled in existing systems?

- What would be a better workflow?

Screenshots and diagrams all appreciated.

**Comment by mwtsn** [comment]
@chri55mith this is the question on competencies that I am aiming to build into the system.

**Comment by IanWraith** [comment]
In this case are we defining a competency as a PPD (CPD) event e.g attending a course or reading a particular paper or something else ?

**Comment by mwtsn** [comment]
I understood it as competency against a particular course, where a supervisor could set the competency and the guidance, and the participant could enter the whys and how's. 

I am open to guidance, but we do need a clear definition before we can implement a solution.

**Comment by mwtsn** [comment]
@IanWraith For the PPD information do you mean this objective: 

Generation of PPD table-based reports from data stored within the system. 

This is also referenced in issue #13.

If so, what information would be useful to capture?

**Comment by IanWraith** [comment]
My feeling is that we need to allow users to input all the types of PPD allowed by the IST , to date them and mark them with the IST category of development that they belong to.

Can anyone else think of anything more ?

Ian

**Comment by mwtsn** [comment]
@IanWraith what are all the types of PPD allowed by IST? Any chance you could list them and the fields required for each type?

There may be some common elements we can use to come up with a solution.

**Comment by IanWraith** [comment]
Have a look at ..

http://istonline.org.uk/wp-content/uploads/2013/09/PPD-form-IST.docx

which lists them all.

Do you need to see some examples of PPD forms to get a feel for the type of information we need to store ?

Ian

**Comment by mwtsn** [comment]
Hi @IanWraith,

Some forms would be very useful, yes please.  However looking at that document you linked to, it seems that the information that can be captured could be quite "loose". 

What I'm thinking (and @chri55mith @mkjonesuk stop me if you think I'm wrong) is that we could have a "PPD" Custom Post Type in WordPress, that allows each "row" of that table to be added as a "post" with the following fields:

- Number (auto generated)
- Date Completed (optional)
- PPD activity (free text)
- Brief description
- Value obtained
- Points awarded (Am I right in thinking we lock this field down so only a supervisor can award points?)
- Verification (Either multiple document uploads, or links to Journal Entries)
- Category of development (as this list could be extensive, we can use 'tags' here so the participant can tag the PPD in multiple categories

This PPD activity will be linked to the participant, and display on their journal on a certain page.

**Comment by mwtsn** [comment]
However @IanWraith, The above comment defines how we capture PPDs is that the same as competencies?  If now how do we go about capturing those?

**Comment by IanWraith** [comment]
I would say PPD and competencies capture are very different animals which
need to be handled in different ways.

Is PPD capture the priority ?

Ian

**Comment by mwtsn** [comment]
@IanWraith competencies was one of the functional requests that came up actually, but now we have PPD functionality defined that helps too. 

If you could help us to map out the Competency requirements that would be very helpful.

**Comment by IanWraith** [comment]
I can't help you with the competencies I'm afraid as this isn't something I
have dealt with in the past.

Chris or Geoff do you have any thoughts on this ?

**Comment by mwtsn** [comment]
Ok, thank you @IanWraith, @chri55mith can you shed some light? I'll send Geoff an email now to let him know how he can join in the chat.

**Comment by chri55mith** [comment]
@joanward any thoughts? I think we need to be careful not to tailor too specific here.

**Comment by chri55mith** [comment]
I'll see Geoff this week so will help him join the chat.

**Comment by mkjonesuk** [comment]
Hi everyone - Matt and I have been busy with a live site migration today so
I'm only just catching up.

What's the status of everyones login? Do we have everyone on board GitHub
yet?

**Comment by mwtsn** [comment]
@IanWraith, @chri55mith, @joanward, @el1gxh (that last one should be Geoff if it works), Just a quick ping to ask you if you have had any more thoughts into how the 'competencies' functionality should work, or if you can send links to any examples for me I can attempt to construct a solution.

There is this link: http://istonline.org.uk/wp-content/uploads/2014/03/RSciTech-Competencies-form.docx from which I put the following suggestion forward, if you could let me know if I am in the right direction I would appreciate it:

I know we discussed that we cannot duplicate [the linked form's] functionality as the competencies could be endless, I do however have the suggestion that a supervisor be able to add competencies to a participants Journal, with guidance notes, and the participant be able to complete the "how's and why's".

**Comment by el1gxh** [comment]
Thanks Matt,
 I'm now in the discussion I've a little bit of catching up to do due to visitors from China and attending an assessor training course.

**Comment by mwtsn** [comment]
Welcome aboard @el1gxh, sounds like a very busy time! 

I look forward to your input :)

**Comment by el1gxh** [comment]
I'm not sure what others think but the competences should be used from the Professional registration forms  the IST produced, the training programme is a different matter all we need is the ability to build units , for example a question where the trainees can add evidence to prove the have completed the unit. If we can then match these units to the competence for professional registration this will defiantly be helpful. I hope that makes sense.

**Comment by mwtsn** [comment]
@el1gxh I'm afraid I don't have a clear picture of what you mean I'm afraid. 

If you could send me links to the Professional Registration Forms I could take a look.

If you would, could you map out a quick workflow for me that might help a little. For example could it work something like the following:

- A supervisor creates a new 'question' (or 'assignment') to one or more participants journal.
- The supervisor can complete information on the assignment such as:
 - Criteria
 - Marking scores
 - Notes
- The participant can view the assignment within their journal and enter:
 - Assignment response
 - How they met the criteria
 - Mark as completed
 - Supporting evidence (including document uploads)
- A supervisor can view the completed 'assignment' and enter a score against all the relevant marking criteria

So for example, an assignment could be created by a supervisor that looks like the following (and assigned to multiple participants):

# Assignment Title
## Brief
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent urna tellus, accumsan sed rutrum sed, pellentesque vel orci. Cras pharetra finibus lectus ut rhoncus.
## Criteria
1. Suspendisse tortor sem, tempus eu pretium in, semper sollicitudin lorem. 
*5 points*

2. Suspendisse tortor sem, tempus eu pretium in, semper sollicitudin lorem. 
*3 points*

3. Suspendisse tortor sem, tempus eu pretium in, semper sollicitudin lorem. 
*2 points*

---
The participant could compete the following areas:


## Response
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent urna tellus, accumsan sed rutrum sed, pellentesque vel orci. Cras pharetra finibus lectus ut rhoncus.

### Criteria 1:
Suspendisse tortor sem, tempus eu pretium in, semper sollicitudin lorem. 
- Document upload 1
- Document upload 2
Self assessed score *5/5*

---

The supervisor could then view the completed assignment, and add appropriate feedback, as follows:

# Feedback 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent urna tellus, accumsan sed rutrum sed, pellentesque vel orci. Cras pharetra finibus lectus ut rhoncus.

## Marks
### Criteria 1:
Suspendisse tortor sem, tempus eu pretium in, semper sollicitudin lorem. 
*3/5*

---

Would something like that approach work?

**Comment by joanward** [comment]
@mwtsn - @IanWraith sent through a link to the PPD form earlier in this thread - http://istonline.org.uk/wp-content/uploads/2013/09/PPD-form-IST.docx

**Comment by mwtsn** [comment]
Ah, thanks for that @joanward but I'm getting a little confused. That was about capturing PPDs not the competencies wasn't it?

Is a competency and a PPD the same thing? From my notes I have the following: 

"I understood it as competency against a particular course, where a supervisor could set the competency and the guidance, and the participant could enter the whys and how's."

So I was going to implement the PPDs as we mapped out earlier in this thread (PPD" Custom Post Type in WordPress), but I was looking for guidance on how to implement the competencies to meet the above note.

If these are the same thing, then that makes my life easier, however I do remember @el1gxh and @chri55mith talking about the assignment functionality. Perhaps I'm getting this confused with a different feature request completely though.

**Comment by joanward** [comment]
Sorry - I picked out the wrong link - the one that I meant to paste from earlier in the thread was http://istonline.org.uk/wp-content/uploads/2014/03/RSciTech-Competencies-form.docx which shows one of the versions of the competency forms that are needed for professional registration and whilst they might not be exactly what @el1gxh needs for training programme management, it is an important element. 
There are in fact 3 different versions of that form (each associated with a different level of registration) so we need to make sure we cover the requirements of all 3.
If you go to http://istonline.org.uk/professional-registration/
that will give you information about the 3 levels and the competency requirements for each level.

**Comment by mwtsn** [comment]
Ah, that makes more sense now @joanward. 

So the 'Assignment' layout I put forward could meet that with a little tweaking of the fields in theory. @el1gxh do you have anything to add on this?

**Comment by el1gxh** [comment]
That fine if we could add one element to the units part it would be for the supervisors to have the ability to sign off as completed. Apart from that it all sounds fine.

**Comment by mwtsn** [comment]
Great @el1gxh that's great, we are pretty much there then with the definition of these elements. 

We can have the supervisors have the ability to sign it off. If it is signed off should we prevent the participant from being able to edit it afterwards?

**Comment by el1gxh** [comment]
@mwtsn yes only the supervisor can be allowed to re-open it for modifications.

**Comment by mwtsn** [comment]
@chri55mith @el1gxh - quick update - Branch phase-2-1-0 now implements much of the PPD functionality: https://github.com/mkdo/cpd/tree/phase-2-1-0 

I will send a more detailed update via email shortly.

**Comment by mwtsn** [comment]
Competencies functionality has been released in phase 2.2.0
