### ISSUE TITLE
Clarify Joan's wish list

### ISSUE THREAD

**Issue by mwtsn** [mkdo/cpd#14]
@chri55mith please could you ask Joan to join this chat or get her comments on the following. We need clarification of each point.

Users need to be able to log the following:

● Personal Details
● Events / Activity Dates ( to / from / onging )
● Type of Event / Activity ( e.g., seminar, conference, networking, literature review etc )
● Description of Event / Activity
● Value obtained
● Points awarded
● Self-certified or accreditation type
● Type of development ( eq. Work-based, professional, non-work, education etc )
● Competence developed / improved
● General notes on CPD activity
● Upload / store documents ( might need quite large upload sizes) - Security to avoid malicious material being uploaded

Users to be able to pull out reports over specific dates
Trainers to be able to review/annotate/sign-off records - share access? User management - who does setup and how are users managed/deleted? Server security is a big issue if accommodation large number of users

**Comment by mwtsn** [comment]
@mkjonesuk did you take some further notes on this?

**Comment by mkjonesuk** [comment]
@mwtsn yes but it was everything that the system already did.

The only query I have now in hindsight is the large file size @chri55mith do you perhaps know how 'large' this would be?

This is more of a server configuration thing but it's something we can document if users need to change it.

**Comment by mwtsn** [comment]
@mkjonesuk @chri55mith what about the capturing of events? Did we say we would just add a category and location information to Journal entries for that, or was it something different? Also the score.

**Comment by mkjonesuk** [comment]
I think the events were just standard 'Posts' with an extra 'Events'
category.

The location / etc can just be added into the main body of the post.

**Comment by mwtsn** [comment]
Id prefer to add it as meta @mkjonesuk so it can be reported on at a later date. I guess this could be a future feature though (or plugin opportunity)

**Comment by mkjonesuk** [comment]
Hi @joanward - can we get your thoughts on the above list, it should match the notes we had from the branding/demo workshop.

**Comment by joanward** [comment]
Hi
My wish largely revolved around being able to complete the PPD form that Ian supplied in issue discussion #1 - and he supplied a link to that.
In addition to the fields that would be required for the form and the ability to upload supporting documents I think a general notes field would be useful as there always seems to be instances where individuals need to store info that doesn't fit into any of the defined fields.
Trainer access - is associated with CPD training tasks where trainers need to add direction/input for candidates. Also where sign-off and verification of event attendance/training task completion.
I hope that clarifies the background to my wish list.

**Comment by IanWraith** [comment]
I agree with @joanward in that I think the system needs to be tightly bound to the IST way of doing things. If a member logs on who has never done CPD before the system needs to guide them. So they can select the CPD category (and helping them choose) then walking them though the process.

@joanward - I can see the need for supporting document uploading and it would be very nice for me to scan and upload say a certificate for a course I have just taken. However (and this is a big but) scanned documents can be large (often in excess of 1MB each) which could cause us problems/expense with disk space on the server the system sits on. @chri55mith are we running on CICS hardware ? Could this be a problem ?

**Comment by joanward** [comment]
@ianwraith - I take your point about this, and storage could be an issue (and security of course). My thinking was if we want candidates to be able to easily output electronic reports similar to the PPD form then we would want any relevant certs etc to be included. I wonder if linking to cloud storage would be an option - what do you think @chri55mith ?

**Comment by mwtsn** [comment]
@joanward we can of course link to files in cloud storage, but then the responsibility for the maintenance of the files on that storage is taken away from the University. Is this something you would be comfortable with @chri55mith @IanWraith? 

For example, a participant could close down their dropbox account, or dropbox could be bought out and shut down (unlikely, but you get the kind of scenario I am going for).

**Comment by IanWraith** [comment]
Storage wise it all depends. If Sheffield Uni is hosting this then the data could be stored in the CICS filestore which would be my preference. The uploaded data could contain personal info (names , addresses etc) so we have to be careful.

@chri55mith How were you planning on hosting this ?

**Comment by mwtsn** [comment]
Closing this down as this has all been covered in issue 1.
