### ISSUE TITLE
Improved ‘privacy’ functions

### ISSUE THREAD

**Issue by mwtsn** [mkdo/cpd#15]
On this feature: Improved ‘privacy’ functions so sites can appear hidden from search engines OR be password protected.

Who will have permissions to make a journal private? The admin, supervisor or participant? @mkjonesuk @chri55mith if you could let me know.

**Comment by mkjonesuk** [comment]
I'd say all three, right @chri55mith?

**Comment by chri55mith** [comment]
Yes, all three should have the option.
