### ISSUE TITLE
Use portfolio data to auto populate IST applications

### ISSUE THREAD

**Issue by mwtsn** [mkdo/cpd#16]
Need clarification from @chri55mith on what format portfolio data needs to export to populate IST applications.

**Comment by mwtsn** [comment]
@chri55mith could you expand on this detailing what format we need to export the data as? If you have a CSV that would be helpful.

**Comment by chri55mith** [comment]
csv would be helpful but a tidy formatted PDF would also be good.

**Comment by mwtsn** [comment]
Ah @chri55mith I misunderstood, I thought this was going to be an auto import style feature.

Im working on the CSV / PDF export currently (I'm afraid its taken longer than planned). So I'll close this one off, unless you do have a need to auto pull the data into IST applications?

**Comment by chri55mith** [comment]
I don't think we need auto pull of data but easy export and import.
