### ISSUE TITLE
Add self assessment points to activities alongside supervisor points

### ISSUE THREAD

**Issue by mwtsn** [mkdo/cpd#20]

**Comment by mkjonesuk** [comment]
This would be under the Points Awarded section in the editor - a new text box to allow the participants to add their own points (self assessment points).

Existing points will be re-named to 'supervisor points'.

**Comment by mwtsn** [comment]
Added in 2.5.3

**Comment by mkjonesuk** [comment]
This needs some extra work so I'm opening it up so we can get extra info.

**Comment by mkjonesuk** [comment]
Seems to be a mixup - We can see 'Points Awarded - Only a supervisor can award points' but nothing for 'Self Assessment' points.

**Comment by mwtsn** [comment]
The self assessment score needs to be on Activities and also output on the front end table.

**Comment by mwtsn** [comment]
@mkjonesuk @joanward this has been implemented in v3.0.1
