### ISSUE TITLE
Make the categories on activities a drop down, with categories defined in the template

### ISSUE THREAD

**Issue by mwtsn** [mkdo/cpd#21]

**Comment by mwtsn** [comment]
Make this hirachical, and remove ability for participant to add their own.

**Comment by mkjonesuk** [comment]
This needs to HIDE the default Categories for 'participant' users and only show for 'supervisor' users.

Tags should be available for both.

**Comment by mwtsn** [comment]
This is now a checkbox in 2.5.3

**Comment by mwtsn** [comment]
Once you have upgraded to 2.5.3 you will need to configure the site appropriately. You can do this via the following settings screen:

/wp-admin/network/settings.php?page=aspire

<img width="1440" alt="screenshot 2016-03-24 14 59 31" src="https://cloud.githubusercontent.com/assets/2066205/14020893/09bf8232-f1d1-11e5-90a4-ce4975600a28.png">

**Comment by joanward** [comment]
Just tried updating the plugin through Network Settings - Plugins - CPD - 'update now' link and I get the following error message:

_The plugin mkdo-cpd-4d431a1/cpd.php has been deactivated due to an error: Plugin file does not exist._

And the plugin has indeed been deactivated.
Can I just hit the Network Activate link?

Joan

**Comment by mwtsn** [comment]
Hi @joanward,

Thanks for the update, I will investigate that.

Yes it should be as simple as clicking Network Activate. 

After you have updated you will have an options screen that will allow you to choose how taxonomies are displayed, you will need to configure this for how you intend to use it. The page is here: http://istcpd.org/wp-admin/network/settings.php?page=aspire

**Comment by joanward** [comment]
Do I need to wait until you have checked this out before I reactivate?

**Comment by mwtsn** [comment]
No @joanward, you will be fine to activate it.

**Comment by joanward** [comment]
That looks fine and the Plugins list is showing the correct version of the Plugin now.
