### ISSUE TITLE
Error adding user

### ISSUE THREAD

**Issue by chri55mith** [mkdo/cpd#24]
Receive the following error when adding a new user in the network admin dashboard:

Warning: Invalid argument supplied for foreach() in /webusers/bo6cpd/public_html/wp-content/plugins/cpd/admin/cpd-users.php on line 457

Warning: Cannot modify header information - headers already sent by (output started at /webusers/bo6cpd/public_html/wp-content/plugins/cpd/admin/cpd-users.php:457) in /webusers/bo6cpd/public_html/wp-includes/pluggable.php on line 1196

Also received the same error when updating the user that had just been created. 

CPD Version 2.4.2

**Comment by mwtsn** [comment]
Hi @chri55mith does the functionality work correctly, however the error is just at the top of the page? Or does the whole thing crash out?

**Comment by mwtsn** [comment]
The latest version (2.4.3) should fix this issue. Please could you upgrade (once it becomes available to download), test and advise @chri55mith
