### ISSUE TITLE
Doesn't create new journal when selecting create new journal

### ISSUE THREAD

**Issue by chri55mith** [mkdo/cpd#25]
When creating a new user, selecting the drop down menu to create a new journal, doesn't create a new journal.

CPD Version 2.4.2

**Comment by mwtsn** [comment]
@chri55mith on which page is this? There are a few places you can create a new Journal. 

Do you get an error message?

**Comment by chri55mith** [comment]
No error. This is on the users edit page within the network dashboard:

/wp-admin/network/user-edit.php?user_id=42&wp_http_referer=%2Fwp-admin%2Fnetwork%2Fusers.php

No error, it just ignores the request.

**Comment by mwtsn** [comment]
@chri55mith can you create the Journal using /wp-admin/users.php?page=cpd_settings_users instead?

**Comment by mwtsn** [comment]
@chri55mith Note that the Journal was created, however it doesn't get automatically assigned.

<img width="1084" alt="screenshot 2015-09-23 15 00 14" src="https://cloud.githubusercontent.com/assets/2066205/10047028/f2dab81e-6203-11e5-8420-5a44bd470a56.png">

If you use the new ['Manage User' Screens](https://github.com/mkdo/cpd/wiki/System-Administrator-User-Guide#user-management) things should be a little easier to manage.

**Comment by chri55mith** [comment]
I will test creating a user via the /wp-admin/users.php next week.
