### ISSUE TITLE
Dashboard menu glitch

### ISSUE THREAD

**Issue by chri55mith** [mkdo/cpd#26]
Strange behaviour in the dashboard menus. Text goes invisible on mouse over and menu's overlap and hide each other.
CPD Version 2.4.2

**Comment by mwtsn** [comment]
@chri55mith Could you provide a screenshot? Also which page is this on?

**Comment by chri55mith** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/11389908/10046515/09463888-6201-11e5-9f81-712bfb3a0919.jpg)

**Comment by mwtsn** [comment]
@chri55mith I have logged on to your server, and I cannot recreate this issue. However I note that the plugin version is 2 versions behind on your server, and WordPress needs upgrading. If you perform these upgrades and you still experience an issue, please let me know.

**Comment by chri55mith** [comment]
updated but got this: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums.

**Comment by mwtsn** [comment]
@chri55mith if that was when you upgraded WordPress I'm afraid you will have to get help in the WordPress support forums.

**Comment by chri55mith** [comment]
![menu-error](https://cloud.githubusercontent.com/assets/11389908/10094771/e42214b2-635b-11e5-879e-3425c1b3b4c8.jpg)

This is related to the CPD plugin or theme. This menu items overlap and disappear. I don't have this problem with any other wordpress dashboard.

**Comment by mwtsn** [comment]
@chri55mith when I VPN onto the server (http://cpd.staff.shef.ac.uk)  and log in as bo6cpd I cannot see this error.

Also note that the CPD plugin is not at the latest version on this server, which may cause you issues.

Can you confirm:

- The server you are using
- The User you are logged in as

Could you also send me the output that you get when you right click and 'view source' on the web page. As it looks like there is a debug error message that is showing which is pushing down the menu item, but its hidden behind the menu.

That should be everything I need to resolve this issue.

**Comment by chri55mith** [comment]
CPD plugin Version 2.4.3 (latest)

Theme CPD Version 1.0.4 (latest) also latest version of parent theme.

cpd.staff.shef.ac.uk

logged in as bo1cps

**Comment by chri55mith** [comment]
Won't let me upload the source?

**Comment by chri55mith** [comment]
sent to your email.

**Comment by mwtsn** [comment]
@chri55mith cannot recreate this error with the steps you have provided, it may be a local issue at your end, could you try on a different browser and let me know the results?

<img width="1440" alt="screenshot 2015-09-25 09 38 21" src="https://cloud.githubusercontent.com/assets/2066205/10096425/49127a80-6369-11e5-8f7b-97007847dcf5.png">

**Comment by mwtsn** [comment]
@chri55mith are you still getting this error?

**Comment by chri55mith** [comment]
it seems to have cleared itself. Menu formatting looks fine at the moment.

**Comment by mwtsn** [comment]
Fantastic @chri55mith, I'll close this one down.
