### ISSUE TITLE
New user dashboard URL error

### ISSUE THREAD

**Issue by chri55mith** [mkdo/cpd#27]
I have reproduced the new user profile error, see image attached.

The user cpsmith entered his password for the first time on a newly created account and was taken to the root site, not /cpsmith 

![profile-url-error](https://cloud.githubusercontent.com/assets/11389908/11272500/4f1693da-8ec5-11e5-812b-6ae49234c352.png)

**Comment by mwtsn** [comment]
Cheers Chris,

May I ask which screen you used to create the user?

**Comment by chri55mith** [comment]
I was in the root site dashboard (not network admin).

**Comment by mwtsn** [comment]
@chri55mith Did you use the 'Manage Participants' screen?

**Comment by chri55mith** [comment]
No I used the Add new user.

**Comment by mwtsn** [comment]
@chri55mith Participants and Supervisors should be setup using the Manage Participant and Manage Supervisor screens as detailed in the user guide. 

If you used 'Add New User' you would not have been able to assign the user to a new blog, so without any blog to be directed to, they would see the screen you have shown.

**Comment by chri55mith** [comment]
Understood. My natural urge to click new user was too strong!

**Comment by mwtsn** [comment]
No worries,

Note that after creating the user that way (or anyway) 'Manage Participant' is where you can set the blog. If you miss out this step they wont be assigned to anything.

**Comment by chri55mith** [comment]
Confirmed. I've just deleted the user. Then recreated using manage participants > new user > create new journal. Logged in, works fine.

**Comment by mwtsn** [comment]
Great @chri55mith - Although that page could do with a better way to manage users when there are quite a few I think. I'll add a new issue for that.
