### ISSUE TITLE
User rights - 'authors' not being copied over for content

### ISSUE THREAD

**Issue by mkjonesuk** [mkdo/cpd#29]
When new journals are created content is not copied correctly - issue with WP core update

**Comment by joanward** [comment]
Do it just need the WP version updating to fix this?
Joan

**Comment by mwtsn** [comment]
Hi Joan,

This issue is resolved, version 2.5.2 of the CPD plugin fixes this issue. Just make sure the plugin is that version or greater and it will be resolved.
