### ISSUE TITLE
Table layouts get messy with lots of content

### ISSUE THREAD

**Issue by mkjonesuk** [mkdo/cpd#32]
We need some 'real data' examples of these to be able to investigate

**Comment by mwtsn** [comment]
<img width="1440" alt="screenshot 2016-03-15 13 34 57" src="https://cloud.githubusercontent.com/assets/2066205/13779419/cec129a8-eab2-11e5-8f4b-a8adbeed90e9.png">

We have agreed to remove the 'Guidance' column, which should neaten this up.

**Comment by mwtsn** [comment]
Fixed in 2.5.3 upgrade
