### ISSUE TITLE
Problem with file uploads

### ISSUE THREAD

**Issue by fe1njb** [mkdo/cpd#35]
![wordpress fault 1 - uploads](https://cloud.githubusercontent.com/assets/17926744/13876831/d32f5408-ecfe-11e5-9d24-7de0e6b00fe4.PNG)

![wordpress fault 2 - pic upload](https://cloud.githubusercontent.com/assets/17926744/13876859/ff41eeca-ecfe-11e5-8cc5-ec680bea37b7.PNG)
File uploads are unsuccessful, but then after, appear to be available to use. When trying to use, they don't insert into posts, just a tiny box appears, other trainee also experiencing same problems. Please see attached screen shots

**Comment by mwtsn** [comment]
At first glance, this appears to be an issue with the server config, after testing it seems that files only up to 1mb can be uploaded, and the file type may be restricted.

I will double check if this can be recreated with all plugins turned off to prove this later today and update.

**Comment by joanward** [comment]
Hi Matt
I will look at increasing the file upload limit and see if that resolves this - there shouldn't be any restriction that stops a png file being uploaded but I'll check that out.
Joan

**Comment by mwtsn** [comment]
Thanks Joan (@joanward), 

I will turn the plugin off and do some testing later (after everyone is out of the system) to make sure the plugin isn't causing problems. I'll let you know the result of that.

**Comment by joanward** [comment]
Hi
Tried increasing the php upload limit on the server and it didn't make any difference, so had a rummage around the network settings in WP and found the option in there to limit filesize for uploads and I have increased that to 10MB. The list of allowed file types in there looks fine.

**Comment by fe1em** [comment]
I just tried re-uploading some of my pictures after the file size increase, but I'm still encountering the same issue. The only picture I've been able to successfully upload is a small 43kb png image. Everything else in the jpeg format still fails every time unfortunately.

**Comment by mwtsn** [comment]
Thanks for the update @fe1em, I'll test if this is related to the plugin or not later today and feedback.

**Comment by joanward** [comment]
Hi
I have managed to get png files up to about 700k in but jpg and jpeg files above 500k fail to load completely
J

**Comment by mwtsn** [comment]
Hi Joan (@joanward),

After disabling the plugin and testing on istcpd.org, the issue still persists. Closing the issue as not related to Aspire CPD.

Thoughts are this could be related to:

- The php.ini may need altering and Apache restarting
- A setting in WordPress 
- File permissions within the uploads folder may need altering

**Comment by joanward** [comment]
Hi

 

Thanks, I will have a look at that – this is the first WP installation where I have seen this happen. 

 

Is it OK for me to run the Wordpress version update now?

 

Cheers

Joan

**Comment by mwtsn** [comment]
Hi Joan (@joanward),

The plugin is compatible with the latest version of WordPress, so you should be fine to do so.

**Comment by mwtsn** [comment]
Further to this @joanward these articles may help:

- https://wordpress.org/support/topic/media-files-dont-upload-on-multisite
- https://wordpress.org/support/topic/multisite-unable-to-upload-images
- https://wordpress.org/support/topic/after-installing-multisite-upload-images-wont-work

**Comment by joanward** [comment]
Hi

 

This appears to be ok now – I have just uploaded a jpg file approx. 3MB without any problem.

 

The upload limit for the media library is currently set to 10MB, if we need it set to a higher limit I can revisit that

 

The issue was resolved by adding the following at server level

suhosin.memory_limit = 256M

 

Cheers

Joan
