### ISSUE TITLE
No Diary option on menu

### ISSUE THREAD

**Issue by fe1njb** [mkdo/cpd#36]
Blog page is main page so can see all posts on site view, but no diary menu option. It disappeared after adding entries. Please see attached.
![wordpress fault 3 - missing diary menu](https://cloud.githubusercontent.com/assets/17926744/13876897/3c4ad85e-ecff-11e5-85be-54532bade288.PNG)

**Comment by mwtsn** [comment]
"My Diary" was the name of a Journal Entry, so appeared in the 'Recents Posts" list. 

This entry will have been either:

- No longer on the list (the list only supports so many items)
- Deleted
- Renamed
