### ISSUE TITLE
Alteration if possible

### ISSUE THREAD

**Issue by el1gxh** [mkdo/cpd#38]
Would it be possible to change someting at the bottom of the post entry at the moment its counting pages, could this be changed to months where it hold each months Posts
![pages to months](https://cloud.githubusercontent.com/assets/11436855/13979237/db5835d6-f0ce-11e5-975e-434e952ada98.JPG)

**Comment by mwtsn** [comment]
@el1gxh The pagination area cannot be turned into a month archive, but you can add a "widget" to the sidebar that lists posts by year and month.
