### ISSUE TITLE
Increase media file size upload limit?

### ISSUE THREAD

**Issue by fe1em** [mkdo/cpd#40]
Hello, 

Is it possible to increase the file size for media uploads up from 10MB? This value is fine for pictures but any camera phone videos longer than a few seconds exceeds this total. I have a short clip ~30 seconds long that comes in at 11.9MB, just outside the limit so I can't upload it.

**Comment by mwtsn** [comment]
Hi @fe1em,

This is an issue for your internal IT team. The plugin does not limit file uploads.

**Comment by fe1em** [comment]
Perhaps I'm misunderstanding but when I'm inside my webfolio media page it does say under the select files button that there is a file size limit of 10MB:

![file zise limit](https://cloud.githubusercontent.com/assets/17873635/14564742/dd1d35a2-031f-11e6-8899-f5ba1abb6327.png)

**Comment by mwtsn** [comment]
@felem,

Thats related to the settings on the server. The plugin does not limit file upload size.

**Comment by fe1em** [comment]
I see thanks for your help.

**Comment by joanward** [comment]
Hi @fe1em
The upload limit has been increased to 20MB now.
