### ISSUE TITLE
IST CPD TDM new journals paths

### ISSUE THREAD

**Issue by joanward** [mkdo/cpd#42]
Hi
We have been running some testing on the ISTCPD portal and wanted to test out how we would  set things up for a specific group of users, ie the TDM group in Sheffield. So I setup a new installation of Wordpress in a /tdm/ subdirectory of the istcpd.org and installed the CPD plugin and theme, and that went fine (this is separate from the WP instance that was installed in the root, that Geoff has been testing). I setup a superadmin user for the istcpd.org.uk/tdm/ instance and sent login details to the TDM testers. They have been asked to work through your videos to try and setup up users/new journals etc and they started this today. However they appear to have hit a snag, 

I noticed from the confirmation email that they had added a new user:
New user registration on your site TDM CPD Portal:
Username: dgreen
Email: tdm@sheffield.ac.uk

And then they added a new site/Journal for DGreen:
New Site: CPD Journal for dgreen
URL: http://istcpd.org/dgreen
Remote IP: 143.167.135.222
Disable these notifications: http://istcpd.org/tdm/wp-admin/network/settings.php

As you can see from the new site/Journal confirmation email the url of the new site is pointing to the istcpd.org root rather than the /tdm/ subdirectory, so we have path problems.

Can you advise please.

**Comment by mwtsn** [comment]
Hi @joanward,

This issue isn't caused by the plugin, it is a well known WordPress Multisite issue, which is notoriously bad at working within a sub folder.

The best advice I can give is to follow the information here: http://wordpress.stackexchange.com/questions/76913/moving-a-wp-multisite-to-a-subdirectory which may help a little.

**Comment by joanward** [comment]
Hi Matt

 

I’m not moving the WPMU installation from the root to subdirectory (/tdm/) – I am trying to run 2 different installations of WPMU in parallel ie. one in the root and one in the /tdm/ subdirectory. The article appears to be about moving WPMU from the root to a subdomain?

 

Joan

**Comment by mwtsn** [comment]
@joanward you will still have all the same issues if you are trying to run Multisite from a sub domain. The article covers some of the issues you might face.
