### ISSUE TITLE
Mass user imports - supervision

### ISSUE THREAD

**Issue by joanward** [mkdo/cpd#43]
Hi
We currently have Exeter Uni starting to trial the software with their techs and I have had the following enquiry from them:

Is there a way to setup users/participants using a spreadsheet import?  Otherwise I have 192 individual entries to do and then all the supervisory alignment to do after that…looking for a shortcut if you know of one.

Are you aware of a WP-MS import facility/plugin that we can use for this?

Also if you set up a participant with their own Journal who also manages other staff, how can they be assigned as supervisors for other Journals if they are already in the system as a participant?

Hope that makes sense.
Thanks
Joan

**Comment by mwtsn** [comment]
Hi @joanward,

There are a few CSV importers available that could do the job in the WordPress repo. They would really have to take a look and assess which ones would work for them. Here is one that I found that may help (however completely untested with the plugin):

https://en-gb.wordpress.org/plugins/import-users-from-csv-with-meta/

With an import script I think they will still have to do the let work of setting up each blog. I will also ask @mkjonesuk as he may know of an alternative importer plugin.

The alternative is for them to contact a WordPress developer (such as ourselves) to write a custom import script for them. 

With regards to setting up a supervisor as a participant, this is not possible currently. You would have to create two accounts for the user, a participant account and a supervisor account.

I hope that clarifies things a little.

Matt

**Comment by joanward** [comment]
Hi
Thanks for the prompt response.
In the case of the importer, if we were to go down the route of a bespoke custom import script, we could presumably use the same script on instances where we install the Aspire plugin? If so I suspect we might want to go that route as I imagine this will be a common issue where the plugin is used for a large group of techs. I will talk to Terry Croft about this and may come back to you, but in the interim if @mkjonesuk has any other suggestions that would be helpful.

If we need to setup 2 accounts where the users are particpants and supervisors then this may give us an issue as the email address can't be used twice, so I will need to look at setting up/using aliases for the additional accounts?

Thanks
Joan
Joan

**Comment by mwtsn** [comment]
Hi @joanward,

Of course, once an import script is written once, it can be used many times. We would aim to open source it. @mkjonesuk would be the man to talk to about this.

With regards to the additional user accounts, you would need aliases for this, I belive this is how Chris handled this when he was trying the system with two roles.

On this, there may be a way to configure it so that a supervisor has a journals of their own, but they would automatically be the supervisor of their own journal, so the alternative account approach gets around this issue.

**Comment by joanward** [comment]
Hi

How would we configure it as per your final paragraph i.e. with a supervisor having their own Journal - would we set up as participant in the first instance with all the various templates setup and then change their role to supervisor? Or am I misunderstanding what you suggest?

Thanks
Joan

On 26 Sep 2016, at 20:34, Matt Watson <notifications@github.com> wrote:

Hi @joanward,

Of course, once an import script is written once, it can be used many times. We would aim to open source it. @mkjonesuk would be the man to talk to about this.

With regards to the additional user accounts, you would need aliases for this, I belive this is how Chris handled this when he was trying the system with two roles.

On this, there may be a way to configure it so that a supervisor has a journals of their own, but they would automatically be the supervisor of their own journal, so the alternative account approach gets around this issue.

**Comment by mwtsn** [comment]
Hi @joanward that should work yes, I'm not 100% sure, I would have to test it out at this end.

However, I'm afraid I'm out of the office, returning in 2 weeks, so I wont be able to look at this until then.
