### ISSUE TITLE
New user passward change

### ISSUE THREAD

**Issue by joanward** [mkdo/cpd#45]
Hi

One of our trials (istcpd-tdm.org)  is reporting that when new participants/users are added - but the link that is included in the introduction email isn't taking them to the correct place to set up their password, instead they have to click on the 'Forgotten Password' link, then use the link in a subsequent email to set the password. Is this right?

**Comment by mwtsn** [comment]
Hi @joanward,

If this config was copied across from another setup, the web address in the wp_options table may be wrong. 

Could you give me an example of where the broken link is taking them please?

**Comment by joanward** [comment]
Hi

 

Its not a copy from another setup – it was a clean setup from scratch.

 

The confirmation/verification email that users get is as follows:

Hi,

You've been invited to join 'TDM CPD Portal' at http://istcpd-tdm.org with the role of Subscriber.

If you do not want to join this site please ignore this email. This invitation will expire in a few days.

 

Please click the following link to activate your user account:

http://istcpd-tdm.org/wp-activate.php?key=be2f00ecc5c3532c

 

But when you click on the link there is an error message showing as follows:

Warning: Cannot modify header information - headers already sent by (output started at /home/istcpdtdm/public_html/wp-content/themes/cpd-theme/header.php:8) in /home/istcpdtdm/public_html/wp-includes/pluggable.php on line 1167

 

What do you advise?

Thanks

Joan

**Comment by mwtsn** [comment]
Hi @joanward thanks for the clarification,

This will need further investigation, an upgrade to WP may have caused this, as I do not recall this issue in previous builds.

**Comment by mwtsn** [comment]
Hi again @joanward do you have access to the PHP error logs on the server? 

If so could you send me them for the particular day/time that this error occurred so I can figure out what is going wrong?

I cannot recreate this end.

**Comment by joanward** [comment]
Hi

 

Sorry Matt, I haven’t forgotten about this I just haven’t had chance to chase this through and get at the error logs, I will try to get something to you in the next few days.

 

Thanks

Joan
