### ISSUE TITLE
Supervisor level users should not be able to edit Participant Journals 

### ISSUE THREAD

**Issue by mkjonesuk** [mkdo/cpd#47]
This is a user roles issue and needs further investigation.

**Comment by mwtsn** [comment]
@joanward @mkjonesuk so supervisors can view participant content, but not edit it? 

This isn't how it has historically been put together, but I should be able to alter that if it is a requirement.

**Comment by mwtsn** [comment]
@joanward @mkjonesuk version 3.0.0 of the plugin implements this.
