### ISSUE TITLE
Removing individual category entries from within journal editor?

### ISSUE THREAD

**Issue by robabbott1** [mkdo/cpd#52]
Is there any way to remove individual category entries from within journal editor?
I've accidentally added my tag entries into the categories list and it's now filled with entries I won't use - Clogging up the list.

**Comment by mwtsn** [comment]
Hi @robabbott1,

To do this you will need an administrator to go into the categories taxonomy and delete unwanted entries.

You can remove entries by unchecking the boxes in the meantime.
