### ISSUE TITLE
Simple theme for journals

### ISSUE THREAD

**Issue by mwtsn** [mkdo/cpd#7]
A simple theme will need creating for all journals to use. 

They should carry a logo that a network admin can assign (so that it can be changed per institution).

@mkjonesuk has a prototype of this in the works.

**Comment by mkjonesuk** [comment]
@mkdo/cpd-partners this is looking like it will be a variant of the TwentyFifteen theme:

https://wordpress.org/themes/twentyfifteen/

Only a single theme will be available for now. In future I'd like to introduce others but we need to limit scope so we can gaurantee delivery.
