### ISSUE TITLE
Theme installer

### ISSUE THREAD

**Issue by mwtsn** [mkdo/cpd#8]
Once the theme is created in issue #7, the plugin needs to be able to either:

- Provide instructions on how to manually install the theme (if a network is locked down so that automatic installations cannot be achieved)

- Automatically install the theme (and potentially fire up a walkthrough wizard to configure it).

**Comment by mkjonesuk** [comment]
@mwtsn not sure this process is right.

The theme and the plugin(s) will be interlinked. I think we need the plugin to throw an error if a 'non registered' theme is activated. 

Otherwise any old theme could be added and it wouldn't automatically show the correct branding and restrictions for example.

I'll work through some ideas for this.

**Comment by mwtsn** [comment]
Remember not everyone will want to use the default @mkjonesuk we should leave it up to the network admin. I recommend we either:

- Make 'force theme' an option (if on it does what you say)
- Just provide guidance to the network admin on how to get up and running and optionally install the theme.

**Comment by chri55mith** [comment]
I prefer the force theme option. Will it re-install twentyfifteen if it is missing?

**Comment by mwtsn** [comment]
That is the plan @chri55mith, or whatever theme is chosen as the default in the config options. 

The only trouble I foresee is if the server is locked down so much that it won't allow the install. If this happens I will provide instructions to:

- Tell the system admin which folders need write access and/or
- Provide instructions on how to do it manually

**Comment by mkjonesuk** [comment]
Also @mwtsn we can point them our way for support/assistance. I'm also wondering if we should come up with guidance around server set-up and access. Likely something we can expand from here: https://wordpress.org/about/requirements/

**Comment by mwtsn** [comment]
Default theme installer, theme and plugin updater and config page now implemented.
